stages:
  - test
  - migration
  - prod

deploy test:
  stage: test
  tags:
    - sia-test
  variables:
    DB_HOST: $DB_TEST_HOST
    DB_NAME: $DB_TEST_NAME
    DB_USER: $DB_TEST_USER
    DB_PASS: $DB_TEST_PASS
    DB_PORT: $DB_TEST_PORT
  script:
    - dotnet tool update --global dotnet-ef --version 3.1.1
    - dotnet ef database update --startup-project Discounting.API/ --project Discounting.Data --context DiscountingDbContext -v
    - docker-compose build
    - docker-compose -f "docker-compose.testing.yml" up -d
    - exit 0
  only:
    - dev


.job-metadata: &job-metadata
  tags:
      - sia-prod
  variables:
    DB_HOST: $DB_PROD_HOST
    DB_NAME: $DB_PROD_NAME
    DB_USER: $DB_PROD_USER
    DB_PASS: $DB_PROD_PASS
    DB_PORT: $DB_PROD_PORT


migration:
  when: manual
  stage: migration
  <<: *job-metadata        
  script:
    - dotnet tool update --global dotnet-ef --version 3.1.1
    - dotnet ef database update --startup-project Discounting.API/ --project Discounting.Data --context DiscountingDbContext -v
  only:
    - master  


deploy prod:
  when: manual
  stage: prod
  <<: *job-metadata        
  script:
    - prepare_infrastructure
    - docker-compose build
    - docker-compose up -d
    - exit 0
  only:
    - master


.functions: &functions |
  function prepare_infrastructure() {
    if [[ $( docker network ls | grep discounting_backend | wc -l ) -ne 1 ]]; then
        docker network create discounting_backend;
    fi
  }
before_script:
  - *functions


