version: '3.8'

services:
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - ./seq-data:/data
    networks:
      - backend
  api:
    image: discounting
    build:
      context: .
      dockerfile: Discounting.API/Dockerfile
    expose:
      - "5000"
    restart: unless-stopped
    volumes:
      - api_data:/app/Uploads/
      - /app/log:/app/log
    depends_on:
      - seq
    networks:
      - backend
    
volumes:
  api_data:
    
networks:
  backend:
    driver: bridge
    name: discounting_backend
